services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: recipe-app
    container_name: recipe-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - recipe-network
    depends_on:
      db:
        condition: service_healthy   # <-- wait for MySQL

  frontend:
    image: node:20-alpine
    container_name: recipe-frontend
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - recipe-network
    depends_on:
      - app

  nginx:
    image: nginx:stable-alpine
    container_name: recipe-nginx
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "9020:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - recipe-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: recipe-mysql
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipe
      MYSQL_USER: recipe
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-host-cache
      --skip-name-resolve
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 15s
    networks:
      - recipe-network
    ports:
      - "3302:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: recipe-phpmyadmin
    restart: unless-stopped
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: recipe
      PMA_PASSWORD: secret
    ports:
      - "9021:80"
    networks:
      - recipe-network
    depends_on:
      - db

networks:
  recipe-network:
    driver: bridge